name: Publish

on:
  push:
    branches: [ "main", "develop", "beta" ]
  pull_request:
    branches: [ "main", "develop", "beta" ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta' }}

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Update npm
        run: npm install -g npm@12

      - name: Install Dependencies
        run: npm ci --ignore-scripts --no-audit

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
